MvcApplication35/Models/Business.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication35.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public int Id { get; set; }
        public string file { get; set; }
        public int SubcategoryId { get; set; }
    
        public virtual BusinessSubcategory BusinessSubcategory { get; set; }
    }
}

MvcApplication35/Models/Finance.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication35.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public int Id { get; set; }
        public string file { get; set; }
        public int SubcategoryId { get; set; }
    
        public virtual FinanceSubcategory FinanceSubcategory { get; set; }
    }
}

MvcApplication35/Models/News.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication35.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string file { get; set; }
        public int SubcategoryId { get; set; }
    
        public virtual NewsSubcategory NewsSubcategory { get; set; }
    }
}

MvcApplication35/Models/upload.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MvcApplication35/Controllers/uploadController.cs
using MvcApplication35.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication35.Controllers
{
    public class uploadController : Controller
    {
        //
        // GET: /upload/
        uploadDBEntities1 db = new uploadDBEntities1();

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Business()
        {
            ViewBag.BusinessCategory = new SelectList(db.BusinessSubcategories, "Id", "SubcategoryName");
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Business(Business t, HttpPostedFileBase file)
        {
            try
            {
                if (file != null)
                {
                    int MaxContentLength = 1024 * 1024 * 60; //60 MB
                    string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf", ".wmv", ".mp4", ".mp3", ".wav", "mpeg", ".wma" };

                    if (!AllowedFileExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                    {
                        // ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions));
                        ViewBag.Message = "Please file of type: " + string.Join(", ", AllowedFileExtensions);
                    }

                    else if (file.ContentLength > MaxContentLength)
                    {
                        return Content("Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/Upload/Business"), fileName);


                        file.SaveAs(path);
                        ModelState.Clear();
                        ViewBag.Message = "File uploaded successfully";
                        string ds = file.FileName.Substring(file.FileName.Length - 3);
                        string p = string.Empty;
                        p = Server.MapPath("~/Content/Upload/Business");
                        file.SaveAs(p + file.FileName);

                        using (db)
                        {

                            t.file = file.FileName;
                            db.Businesses.Add(t);
                            db.SaveChanges();

                        }

                    }

                }
                else
                {
                    return Content("Upload Your file to Continue");
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Home", "Index"));
                throw;
            }

        }

        public ActionResult Finance()
        {
            ViewBag.FinanceCategory = new SelectList(db.FinanceSubcategories, "Id", "SubcategoryName");
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Finance(Finance t, HttpPostedFileBase file)
        {
            try
            {
                if (file != null)
                {
                    int MaxContentLength = 1024 * 1024 * 60; //60 MB
                    string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf", ".html", ".htm", ".wmv", ".mp4", ".mp3", ".wav" };

                    if (!AllowedFileExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                    {
                        // ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions));
                        ViewBag.Message = "Please file of type: " + string.Join(", ", AllowedFileExtensions);
                    }

                    else if (file.ContentLength > MaxContentLength)
                    {
                        return Content("Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/Upload/Finance"), fileName);


                        file.SaveAs(path);
                        ModelState.Clear();
                        ViewBag.Message = "File uploaded successfully";
                        string ds = file.FileName.Substring(file.FileName.Length - 3);
                        string p = string.Empty;
                        p = Server.MapPath("~/Content/Upload/Finance");
                        file.SaveAs(p + file.FileName);

                        using (db)
                        {

                            t.file = file.FileName;
                            db.Finances.Add(t);
                            db.SaveChanges();

                        }

                    }

                }
                else
                {
                    return Content("Upload Your file to Continue");
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View("Error", new HandleErrorInfo(ex, "Home", "Index"));
                throw;
            }


        }

        // News Upload 

        public ActionResult News()
        {
            ViewBag.NewsCategory = new SelectList(db.NewsSubcategories, "Id", "SubcategoryName");
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult News(News t, HttpPostedFileBase file)
        {
            try
            {
                if (file != null)
                {
                    int MaxContentLength = 1024 * 1024 * 60; //60 MB
                    string[] AllowedFileExtensions = new string[] { ".jpg", ".gif", ".png", ".pdf", ".html", ".htm", ".wmv", ".mp4", ".mp3", ".wav" };

                    if (!AllowedFileExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                    {
                        // ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions));
                        ViewBag.Message = "Please file of type: " + string.Join(", ", AllowedFileExtensions);
                    }

                    else if (file.ContentLength > MaxContentLength)
                    {
                        return Content("Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                    }
                    else
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Content/Upload/News"), fileName);


                        file.SaveAs(path);
                        ModelState.Clear();
                        ViewBag.Message = "File uploaded successfully";
                        string ds = file.FileName.Substring(file.FileName.Length - 3);
                        string p = string.Empty;
                        p = Server.MapPath("~/Content/Upload/News");
                        file.SaveAs(p + file.FileName);

                        using (db)
                        {

                            t.file = file.FileName;
                            db.News.Add(t);
                            db.SaveChanges();

                        }

                    }

                }
                else
                {
                    return Content("Upload Your file to Continue");
                }
                return RedirectToAction("Index");
            }

            catch (Exception ex)
            {

                return View("Error", new HandleErrorInfo(ex, "Home", "Index"));
                throw;
            }

        }
    }
}

MvcApplication35/Views/upload/Business.cshtml
@model MvcApplication35.Models.Business

@{
    ViewBag.Title = "Business";
}

<h2>Business</h2>

@using (Html.BeginForm("Business", "upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Business</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            <input type="file" name="file" />
            @Html.ValidationMessageFor(model => model.file)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubcategoryId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(p => p.SubcategoryId, ViewBag.BusinessCategory as SelectList, "Select category of file", new { id = "SubcategoryId" })
            @Html.ValidationMessageFor(model => model.SubcategoryId)
        </div>


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication35/Views/upload/Finance.cshtml
@model MvcApplication35.Models.Finance

@{
    ViewBag.Title = "Finance";
}

<h2>Upload your Finance News Here</h2>

@using (Html.BeginForm("Finance", "upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Business</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            <input type="file" name="file" />
            @Html.ValidationMessageFor(model => model.file)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubcategoryId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(p => p.SubcategoryId, ViewBag.FinanceCategory as SelectList, "Select category of file", new { id = "SubcategoryId" })
            @Html.ValidationMessageFor(model => model.SubcategoryId)
        </div>


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication35/Views/upload/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Welcome</h2>

<script>
    function doNavigate() {
        window.location.href = document.getElementById("UrlList").value;
    }
</script>
<h2>Select the category of the file to be uploaded</h2>
<select id="UrlList" onchange="doNavigate()">
    <option value="">Select a Page...</option>
    <option value="@Url.Action("Business", "upload")">Business</option>
    <option value="@Url.Action("Finance", "upload")">Finance</option>
    <option value="@Url.Action("News", "upload")">News</option>
</select>

MvcApplication35/Views/upload/News.cshtml
@model MvcApplication35.Models.News

@{
    ViewBag.Title = "News";
}

<h2>Upload your News Here</h2>

@using (Html.BeginForm("News", "upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>News</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            <input type="file" name="file" />
            @Html.ValidationMessageFor(model => model.file)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SubcategoryId)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(p => p.SubcategoryId, ViewBag.NewsCategory as SelectList, "Select category of file", new { id = "SubcategoryId" })
            @Html.ValidationMessageFor(model => model.SubcategoryId)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Upload another file", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}