MvcApplication35/Controllers/ProofreadController.cs
using MvcApplication35.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcApplication35.Controllers
{

    public class ProofreadController : Controller
    {

        //

        // GET: /Proofread/

        uploadDBEntities1 db = new uploadDBEntities1();

        public ActionResult Index()
        {

            return View();

        }

        public ActionResult BusinessList()
        {

            return View(db.Businesses.ToList());

        }



        // Get: /FileUpload // Deatails

        public ActionResult BusinessDetails(int id)
        {

            return View(db.Businesses.Find(id));

        }

        // Get: /FileUpload // Edit

        public ActionResult BusinessEdit(int id)
        {

            return View(db.Businesses.Find(id));

        }

        // Post: /Business // Edit

        [HttpPost, ValidateAntiForgeryToken]

        public ActionResult BusinessEdit(Business t, HttpPostedFileBase file)
        {

            if (file != null)
            {

                var fileName = Path.GetFileName(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/Upload/Business"),

                fileName);

                file.SaveAs(path);

                ModelState.Clear();

                ViewBag.Message = "File updated successfully";

                string sd = file.FileName.Substring(file.FileName.Length - 3);

                string p = string.Empty;

                p = Server.MapPath("~/Content/Upload/Business");

                file.SaveAs(p + file.FileName);

                using (db)
                {

                    t.file = file.FileName;

                    db.Entry(t).State = EntityState.Modified;

                    db.SaveChanges();

                }

            }

            return RedirectToAction("BusinessList");

        }

        // Get: /Business // Delete

        public ActionResult BusinessDelete(int id)
        {

            return View(db.Businesses.Find(id));

        }

        // Post: /Business // Delete

        [HttpPost, ActionName("BusinessDelete")]

        public ActionResult Businessdelete_conf(int id)
        {

            Business t = db.Businesses.Find(id);

            db.Businesses.Remove(t);

            db.SaveChanges();

            return RedirectToAction("BusinessList");

        }

        // Finance List

        public ActionResult FinanceList()
        {

            return View(db.Finances.ToList());

        }

        // Get: /Finances // Deatails

        public ActionResult FinanceDetails(int id)
        {

            return View(db.Finances.Find(id));

        }

        // Get / finance // edit

        public ActionResult FinanceEdit(int id)
        {

            return View(db.Finances.Find(id));

        }

        // Post: /Finance // Edit

        [HttpPost, ValidateAntiForgeryToken]

        public ActionResult FinanceEdit(Finance t, HttpPostedFileBase file)
        {

            if (file != null)
            {

                var fileName = Path.GetFileName(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/Upload/Finance"),

                fileName);

                file.SaveAs(path);

                ModelState.Clear();

                ViewBag.Message = "File updated successfully";

                string sd = file.FileName.Substring(file.FileName.Length - 3);

                string p = string.Empty;

                p = Server.MapPath("~/Content/Upload/Finance");

                file.SaveAs(p + file.FileName);

                using (db)
                {

                    t.file = file.FileName;

                    db.Entry(t).State = EntityState.Modified;

                    db.SaveChanges();

                }

            }

            return RedirectToAction("FinanceList");

        }

        // Get: /Finance // Delete

        public ActionResult FinanceDelete(int id)
        {

            return View(db.Finances.Find(id));

        }

        // Post: /Finance // Delete

        [HttpPost, ActionName("FinanceDelete")]

        public ActionResult Financedelete_conf(int id)
        {

            Finance t = db.Finances.Find(id);

            db.Finances.Remove(t);

            db.SaveChanges();

            return RedirectToAction("FinanceList");

        }

        // News List

        public ActionResult NewsList()
        {

            return View(db.News.ToList());

        }

        // Get: /News // Details

        public ActionResult NewsDetails(int id)
        {

            return View(db.News.Find(id));

        }

        // Get / News // edit

        public ActionResult NewsEdit(int id)
        {

            return View(db.News.Find(id));

        }

        // Post: /News // Edit

        [HttpPost, ValidateAntiForgeryToken]

        public ActionResult NewsEdit(News t, HttpPostedFileBase file)
        {

            if (file != null)
            {

                var fileName = Path.GetFileName(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/Upload/News"),

                fileName);

                file.SaveAs(path);

                ModelState.Clear();

                ViewBag.Message = "File updated successfully";

                string sd = file.FileName.Substring(file.FileName.Length - 3);

                string p = string.Empty;

                p = Server.MapPath("~/Content/Upload/News");

                file.SaveAs(p + file.FileName);

                using (db)
                {

                    t.file = file.FileName;

                    db.Entry(t).State = EntityState.Modified;

                    db.SaveChanges();

                }

            }

            return RedirectToAction("NewsList");

        }

        //News delete

        // Get: /News // Delete

        public ActionResult NewsDelete(int id)
        {

            return View(db.News.Find(id));

        }

        // Post: /News // Delete

        [HttpPost, ActionName("NewsDelete")]

        public ActionResult Newsdelete_conf(int id)
        {

            News t = db.News.Find(id);

            db.News.Remove(t);

            db.SaveChanges();

            return RedirectToAction("NewsList");

        }

    }

}

MvcApplication35/Views/Proofread/BusinessDelete.cshtml
@model MvcApplication35.Models.Business

@{
    ViewBag.Title = "BusinessDelete";
}

@*<h2>BusinessDelete</h2>*@

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Business</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.file)
    </div>
    <div class="editor-field">
        @*<input type="file" name="file" />*@
        @{
            if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".jpg") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".gif") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".png"))
            {
                <img src="~/Content/Upload/Business/@Model.file" alt="image" width="100" />
                @Html.ValidationMessageFor(model => model.file)
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp3") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wav") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wma"))
            {
                <audio controls>
                    <source src="~/Content/Upload/Business/@Model.file" alt="audio" type="audio/mp3" />
                </audio>
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp4") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wmv") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".mpeg"))
            {
                <video height="500" width="700" controls>
                    <source src="~/Content/Upload/Business/@Model.file" alt="video" type="video/webm" width="300" height="300" />
                </video>
            }
        }
    </div>


</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcApplication35/Views/Proofread/BusinessDetails.cshtml
@model MvcApplication35.Models.Business

@{
    ViewBag.Title = "BusinessDetails";
}

<h2>BusinessDetails</h2>

<fieldset>
    <legend>Business</legend>

    <div class="editor-field">
        @*<input type="file" name="file" />*@
        @{
            if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".jpg") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".gif") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".png"))
            {
                <img src="~/Content/Upload/Business/@Model.file" alt="image" width="100" />
                @Html.ValidationMessageFor(model => model.file)
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp3") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wav") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wma"))
            {
                <audio controls>
                    <source src="~/Content/Upload/Business/@Model.file" alt="audio" type="audio/mp3" />
                </audio>
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp4") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wmv") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".mpeg"))
            {
                <video height="500" width="700" controls>
                    <source src="~/Content/Upload/Business/@Model.file" alt="video" type="video/webm" width="300" height="300" />
                </video>
            }
        }
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.SubcategoryId)
    </div>
    <div class="display-field">
        @*@Html.DisplayFor(model => model.SubcategoryId)*@


        @*@Html.DisplayFor(model => model.Category)*@
        @{
            string txt = "";
            if (Model.SubcategoryId == 1)
            {
                txt = "Technology";
            }
            else if (Model.SubcategoryId == 2)
            {
                txt = "RealEstate";
            }
            else if (Model.SubcategoryId == 3)
            {
                txt = "SmallBusiness";
            }
            else if (Model.SubcategoryId == 4)
            {
                txt = "Contract";
            }
        }
        @Html.DisplayFor(model => txt)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "BusinessEdit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "BusinessList")
</p>

MvcApplication35/Views/Proofread/BusinessEdit.cshtml
@model MvcApplication35.Models.Business

@{
    ViewBag.Title = "BusinessEdit";
}

<h2>BusinessEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Business</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            <input type="file" name="file" />
            @{
    if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".jpg") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".gif") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".png"))
    {
        <img src="~/Content/Upload/Business/@Model.file" alt="image" width="100" />
                @Html.ValidationMessageFor(model => model.file)
    }
    else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp3") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wav") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wma"))
    {
        <audio controls>
            <source src="~/Content/Upload/Business/@Model.file" alt="audio" type="audio/mp3" />
        </audio>
    }
    else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp4") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wmv") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".mpeg"))
    {
        <video height="500" width="700" controls>
            <source src="~/Content/Upload/Business/@Model.file" alt="video" type="video/webm" width="300" height="300" />
        </video>
    }
            }


        </div>

        @*<div class="editor-label">
                @Html.LabelFor(model => model.SubcategoryId)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.SubcategoryId)
                @Html.ValidationMessageFor(model => model.SubcategoryId)
            </div>*@

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication35/Views/Proofread/BusinessList.cshtml
@model IEnumerable<MvcApplication35.Models.Business>

@{
    ViewBag.Title = "BusinessList";
}

<h2>BusinessList</h2>


<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.file)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubcategoryId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.file)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.Category)*@
                @{
        string txt = "";
        if (item.SubcategoryId == 1)
        {
            txt = "Technology";
        }
        else if (item.SubcategoryId == 2)
        {
            txt = "RealEstate";
        }
        else if (item.SubcategoryId == 3)
        {
            txt = "SmallBusiness";
        }
        else if (item.SubcategoryId == 4)
        {
            txt = "Contract";
        }
                }
                @Html.DisplayFor(modeItem => txt)

            </td>
            <td>
                @Html.ActionLink("Verify", "BusinessEdit", new { id = item.Id }) |
                @Html.ActionLink("Details", "BusinessDetails", new { id = item.Id }) |
                @Html.ActionLink("Delete", "BusinessDelete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

MvcApplication35/Views/Proofread/FinanceDelete.cshtml
@model MvcApplication35.Models.Finance

@{
    ViewBag.Title = "FinanceDelete";
}

<h2>FinanceDelete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Finance</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.file)
    </div>
    <div class="editor-field">
        @*<input type="file" name="file" />*@
        @{
            if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".jpg") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".gif") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".png"))
            {
                <img src="~/Content/Upload/Finance/@Model.file" alt="image" width="100" />
                @Html.ValidationMessageFor(model => model.file)
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp3") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wav") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wma"))
            {
                <audio controls>
                    <source src="~/Content/Upload/Finance/@Model.file" alt="audio" type="audio/mp3" />
                </audio>
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp4") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wmv") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".mpeg"))
            {
                <video height="500" width="700" controls>
                    <source src="~/Content/Upload/Finance/@Model.file" alt="video" type="video/webm" width="300" height="300" />
                </video>
            }
        }
    </div>

    @*<div class="display-label">
             @Html.DisplayNameFor(model => model.SubcategoryId)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.SubcategoryId)
        </div>*@
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MvcApplication35/Views/Proofread/FinanceDetails.cshtml
@model MvcApplication35.Models.Finance

@{
    ViewBag.Title = "FinanceDetails";
}

<h2>FinanceDetails</h2>

<fieldset>
    <legend>Finance</legend>

    <div class="display-field">
        @*<input type="file" name="file" />*@
        @{
            if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".jpg") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".gif") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".png"))
            {
                <img src="~/Content/Upload/Finance/@Model.file" alt="image" width="100" />
                @Html.ValidationMessageFor(model => model.file)
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp3") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wav") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wma"))
            {
                <audio controls>
                    <source src="~/Content/Upload/Finance/@Model.file" alt="audio" type="audio/mp3" />
                </audio>
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp4") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wmv") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".mpeg"))
            {
                <video height="500" width="700" controls>
                    <source src="~/Content/Upload/Finance/@Model.file" alt="video" type="video/webm" width="300" height="300" />
                </video>
            }
        }
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.SubcategoryId)
    </div>
    <div class="display-field">
        @{
            string txt = "";
            if (Model.SubcategoryId == 1)
            {
                txt = "Market";
            }
            else if (Model.SubcategoryId == 2)
            {
                txt = "Stocks";
            }
            else if (Model.SubcategoryId == 3)
            {
                txt = "Currency";
            }
            else if (Model.SubcategoryId == 4)
            {
                txt = "Economy";
            }
        }
        @Html.DisplayFor(modeItem => txt)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "FinanceList")
</p>

MvcApplication35/Views/Proofread/FinanceEdit.cshtml
@model MvcApplication35.Models.Finance

@{
    ViewBag.Title = "FinanceEdit";
}

<h2>FinanceEdit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Finance</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.file)
        </div>
        <div class="editor-field">
            <input type="file" name="file" />
            @{
    if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".jpg") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".gif") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".png"))
    {
        <img src="~/Content/Upload/Finance/@Model.file" alt="image" width="100" />
                @Html.ValidationMessageFor(model => model.file)
    }
    else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp3") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wav") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wma"))
    {
        <audio controls>
            <source src="~/Content/Upload/Finance/@Model.file" alt="audio" type="audio/mp3" />
        </audio>
    }
    else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp4") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wmv") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".mpeg"))
    {
        <video height="500" width="700" controls>
            <source src="~/Content/Upload/Finance/@Model.file" alt="video" type="video/webm" width="300" height="300" />
        </video>
    }
            }
            @Html.ValidationMessageFor(model => model.file)
        </div>

        @*<div class="editor-label">
                @Html.LabelFor(model => model.SubcategoryId)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.SubcategoryId)
                @Html.ValidationMessageFor(model => model.SubcategoryId)
            </div>*@

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "FinanceList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MvcApplication35/Views/Proofread/FinanceList.cshtml
@model IEnumerable<MvcApplication35.Models.Finance>

@{
    ViewBag.Title = "FinanceList";
}

<h2>FinanceList</h2>


<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.file)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubcategoryId)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.file)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.SubcategoryId)*@
                @{
        string txt = "";
        if (item.SubcategoryId == 1)
        {
            txt = "Market";
        }
        else if (item.SubcategoryId == 2)
        {
            txt = "Stocks";
        }
        else if (item.SubcategoryId == 3)
        {
            txt = "Currency";
        }
        else if (item.SubcategoryId == 4)
        {
            txt = "Economy";
        }
                }
                @Html.DisplayFor(modeItem => txt)


            </td>
            <td>
                @Html.ActionLink("Verify", "FinanceEdit", new { id = item.Id }) |
                @Html.ActionLink("Details", "FinanceDetails", new { id = item.Id }) |
                @Html.ActionLink("Delete", "FinanceDelete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

MvcApplication35/Views/Proofread/Index.cshtml
@{

    ViewBag.Title = "Index";

}

<h2>Welcome</h2>

<script>

function doNavigate() {

window.location.href = document.getElementById("UrlList").value;

}

</script>

<h2>Select the category of the file to Proofread</h2>

<select id="UrlList" onchange="doNavigate()">

    <option value="">Select a Page...</option>

    <option value="@Url.Action("BusinessList", "Proofread")">Business</option>

    <option value="@Url.Action("FinanceList", "Proofread")">Finance</option>

    <option value="@Url.Action("NewsList", "Proofread")">News</option>

</select>

MvcApplication35/Views/Proofread/NewsDelete.cshtml
@model MvcApplication35.Models.News

@{
    ViewBag.Title = "NewsDelete";
}

<h2>NewsDelete</h2>
<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>News</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.file)
    </div>
    <div class="editor-field">
        <input type="file" name="file" />
        @{
            if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".jpg") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".gif") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".png"))
            {
                <img src="~/Content/Upload/News/@Model.file" alt="image" width="100" />
                @Html.ValidationMessageFor(model => model.file)
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp3") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wav") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wma"))
            {
                <audio controls>
                    <source src="~/Content/Upload/News/@Model.file" alt="audio" type="audio/mp3" />
                </audio>
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp4") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wmv") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".mpeg"))
            {
                <video height="500" width="700" controls>
                    <source src="~/Content/Upload/News/@Model.file" alt="video" type="video/webm" width="300" height="300" />
                </video>
            }
        }
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.SubcategoryId)
    </div>
    <div class="display-field">
        @*@Html.DisplayFor(model => model.SubcategoryId)*@
        @{
            string txt = "";
            if (Model.SubcategoryId == 1)
            {
                txt = "Sports";
            }
            else if (Model.SubcategoryId == 2)
            {
                txt = "Education";
            }
            else if (Model.SubcategoryId == 3)
            {
                txt = "Weather";
            }
            else if (Model.SubcategoryId == 4)
            {
                txt = "Politics";
            }
        }
        @Html.DisplayFor(modeItem => txt)
    </div>
</fieldset>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "NewsList")
    </p>
}

MvcApplication35/Views/Proofread/NewsDetails.cshtml
@model MvcApplication35.Models.News

@{
    ViewBag.Title = "NewsDetails";
}

<h2>NewsDetails</h2>

<fieldset>
    <legend>News</legend>


    <div class="display-field">
        @*<input type="file" name="file" />*@
        @{
            if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".jpg") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".gif") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".png"))
            {
                <img src="~/Content/Upload/News/@Model.file" alt="image" width="100" />
                @Html.ValidationMessageFor(model => model.file)
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp3") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wav") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wma"))
            {
                <audio controls>
                    <source src="~/Content/Upload/News/@Model.file" alt="audio" type="audio/mp3" />
                </audio>
            }
            else if ((Model.file.Substring(Model.file.LastIndexOf('.')) == ".mp4") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".wmv") || (Model.file.Substring(Model.file.LastIndexOf('.')) == ".mpeg"))
            {
                <video height="500" width="700" controls>
                    <source src="~/Content/Upload/News/@Model.file" alt="video" type="video/webm" width="300" height="300" />
                </video>
            }
        }
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.SubcategoryId)
    </div>
    <div class="display-field">
        @{
            string txt = "";
            if (Model.SubcategoryId == 1)
            {
                txt = "Sports";
            }
            else if (Model.SubcategoryId == 2)
            {
                txt = "Education";
            }
            else if (Model.SubcategoryId == 3)
            {
                txt = "Weather";
            }
            else if (Model.SubcategoryId == 4)
            {
                txt = "Politics";
            }
        }
        @Html.DisplayFor(modeItem => txt)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "NewsList")
</p>